name: Generate plantuml diagram

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SVG Diagram
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg diagrams/*.puml